title: USDM FSA LFP County Aggregations
description: Weekly US Drought Monitor (USDM) data aggregated to FSA LFP county boundaries
author: R. Kyle Bocinsky
url: "https://strong-fsa.github.io/usdm-counties-fsa-lfp/"  # Your GitHub Pages URL
baseurl: "/usdm-counties-fsa-lfp"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# minima:
#   skin: classic